
import type { Site, Language, View, Alert } from './types';
import { StatusLevel } from './types';
import { DashboardIcon, AlertIcon, ReportsIcon, SettingsIcon, UsersIcon } from './components/icons/NavIcons';
import { FanIcon, BulbIcon, ShutdownIcon } from './components/icons/MetricIcons';

export const SITES: Site[] = [
  { id: 'site_a', nameKey: 'site_a' },
  { id: 'site_b', nameKey: 'site_b' },
  { id: 'site_c', nameKey: 'site_c' },
];

export const NAV_ITEMS: { id: View; icon: React.FC<React.SVGProps<SVGSVGElement>> }[] = [
  { id: 'dashboard', icon: DashboardIcon },
  { id: 'alerts', icon: AlertIcon },
  { id: 'ventilation', icon: FanIcon },
  { id: 'lighting', icon: BulbIcon },
  { id: 'emergency', icon: ShutdownIcon },
  { id: 'reports', icon: ReportsIcon },
  { id: 'users', icon: UsersIcon },
  { id: 'settings', icon: SettingsIcon },
];

export const initialMockAlerts: Alert[] = [
  { id: '1', siteId: 'site_a', parameter: 'membrane_health', message: 'membrane_defect_alert', severity: StatusLevel.Danger, timestamp: new Date(Date.now() - 3600000).toISOString(), status: 'active' },
  { id: '2', siteId: 'site_a', parameter: 'internal_air_quality_co2', message: 'high_co2_alert', severity: StatusLevel.Warn, timestamp: new Date(Date.now() - 7200000).toISOString(), status: 'active' },
  { id: '3', siteId: 'site_b', parameter: 'internal_pressure', message: 'high_pressure_alert', severity: StatusLevel.Warn, timestamp: new Date(Date.now() - 86400000).toISOString(), status: 'resolved' },
  { id: '4', siteId: 'site_a', parameter: 'internal_noise_level', message: 'noise_level_alert', severity: StatusLevel.Warn, timestamp: new Date(Date.now() - 172800000).toISOString(), status: 'acknowledged' },
  { id: '5', siteId: 'site_c', parameter: 'power_consumption', message: 'high_pressure_alert', severity: StatusLevel.Warn, timestamp: new Date(Date.now() - 172800000).toISOString(), status: 'active' },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // General
    'app_title': 'Air Dome Intelligence Dashboard',
    'select_site': 'Select Site',
    'site': 'Site',
    'status': 'Status',
    'normal': 'Normal',
    'defect_detected': 'Defect Detected',
    'on': 'On',
    'off': 'Off',
    'open': 'Open',
    'closed': 'Closed',
    'get_ai_analysis': 'Get AI Analysis',
    'ai_analysis_title': 'AI Dome Health Analysis',
    'generating_analysis': 'Generating analysis...',
    'close': 'Close',
    'error_generating_analysis': 'Error generating analysis. Please try again.',
    'historical_data': 'Historical Data',
    'now_label': 'Now',
    'internal': 'Internal',
    'external': 'External',
    'running': 'Running',
    '30_minutes': '30 Minutes',
    '1_hour': '1 Hour',
    '6_hours': '6 Hours',
    '12_hours': '12 Hours',
    '24_hours': '24 Hours',
    'logout': 'Logout',
    'login': 'Login',
    'username': 'Username',
    'password': 'Password',
    'logging_in': 'Logging in...',
    'invalid_credentials': 'Invalid username or password.',
    'dont_have_account': "Don't have an account?",
    'register_now': 'Register now',


    // Sites
    'site_a': 'Site A',
    'site_b': 'Site B',
    'site_c': 'Site C',

    // Views
    'dashboard': 'Dashboard',
    'alerts': 'Alerts',
    'ventilation': 'Ventilation Control',
    'lighting': 'Lighting Control',
    'emergency': 'Emergency Shutdown',
    'reports': 'Reports',
    'settings': 'Settings',
    'users': 'Users',
    
    // Paired Parameters
    'pressure': 'Pressure',
    'temperature': 'Temperature',
    'humidity': 'Humidity',
    'pm25': 'PM2.5',
    'co2': 'CO2',
    'o2': 'O2',
    'co': 'CO',
    'noise': 'Noise',

    // Parameters
    'internal_pressure': 'Internal Pressure',
    'external_pressure': 'External Pressure',
    'fan_speed': 'Fan Speed',
    'air_exchange_rate': 'Air Exchange Rate',
    'power_consumption': 'Power Consumption',
    'voltage': 'Voltage',
    'current': 'Current',
    'external_wind_speed': 'External Wind Speed',
    'internal_air_quality_pm25': 'Internal (PM2.5)',
    'external_air_quality_pm25': 'External (PM2.5)',
    'internal_air_quality_co2': 'Internal (CO2)',
    'external_air_quality_co2': 'External (CO2)',
    'internal_air_quality_o2': 'Internal (O2)',
    'external_air_quality_o2': 'External (O2)',
    'internal_air_quality_co': 'Internal (CO)',
    'external_air_quality_co': 'External (CO)',
    'internal_temperature': 'Internal Temperature',
    'external_temperature': 'External Temperature',
    'internal_humidity': 'Internal Humidity',
    'external_humidity': 'External Humidity',
    'membrane_health': 'Membrane Health',
    'internal_noise_level': 'Internal Noise Level',
    'external_noise_level': 'External Noise Level',
    'base_corner_pressure': 'Base Corner Pressure',
    'internal_lux_level': 'Internal Lux Level',
    'internal_lighting_status': 'Internal Lighting Status',
    'air_shutter_status': 'Air Shutter Status',
    
    // Metric Groups
    'dome_integrity': 'Dome Integrity',
    'environment': 'Environment',
    'air_quality': 'Air Quality',
    'systems_status': 'Systems Status',
    'power': 'Power',

    // Alerts
    'active_alerts': 'Active Alerts',
    'alert_history': 'Alert History',
    'parameter': 'Parameter',
    'message': 'Message',
    'severity': 'Severity',
    'timestamp': 'Timestamp',
    'action': 'Action',
    'high_pressure_alert': 'High pressure detected',
    'membrane_defect_alert': 'Potential membrane defect detected',
    'high_co2_alert': 'CO2 levels are high',
    'noise_level_alert': 'High noise levels detected',
    'low': 'Low',
    'medium': 'Medium',
    'high': 'High',
    'acknowledge': 'Acknowledge',
    'no_active_alerts': 'No active alerts for this site.',
    
    // Controls
    'ventilation_control': 'Ventilation Control',
    'lighting_control': 'Lighting Control',
    'main_lighting': 'Main Lighting',
    'brightness': 'Brightness',
    'fan_set_control': 'Fan Set Control',
    'fan_set': 'Fan Set',
    'inflow_volume': 'Inflow Volume',
    'outflow_volume': 'Outflow Volume',
    'auto': 'Auto',
    'manual': 'Manual',
    'mode': 'Mode',
    'shutdown_fan': 'Shutdown Fan',
    'power_on_fan': 'Power On Fan',
    'power_on_lights': 'Power On Lights',
    'power_off_lights': 'Shutdown Lights',
    'other_controls': 'Other Controls',

    // Emergency Shutdown
    'emergency_shutdown': 'Emergency Shutdown',
    'emergency_shutdown_title': 'Emergency Shutdown Protocol',
    'initiate_shutdown': 'Initiate Shutdown Sequence',
    'shutdown_warning': 'Warning: This action will immediately begin a full system shutdown. This is for extreme emergencies only and may require on-site personnel for a full system restart.',
    'confirm_shutdown_title': 'Confirmation Required',
    'confirm_shutdown_message': "Are you absolutely sure you want to shut down all dome systems? This action cannot be undone from this dashboard.",
    'confirm_shutdown_button': 'Yes, Shut Down Everything',
    'cancel_shutdown_button': 'Cancel',
    'shutdown_in_progress': 'Shutdown in Progress...',
    'shutdown_step_1': 'Disengaging fan controllers...',
    'shutdown_step_2': 'Deactivating lighting circuits...',
    'shutdown_step_3': 'Securing airlocks and disabling pressure sensors...',
    'shutdown_step_4': 'Finalizing system halt...',
    'shutdown_complete_title': 'System Shutdown Complete',
    'shutdown_complete_message': 'All systems have been safely brought offline. The dome is now in a safe, unpowered state.',
    'reset_simulation': 'Reset Simulation',
    
    // Reports
    'generate_report': 'Generate Report',
    'report_type': 'Report Type',
    'time_range': 'Time Range',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'export_pdf': 'Export as PDF',
    'export_csv': 'Export as CSV',

    // Settings
    'language_settings': 'Language Settings',
    'english': 'English',
    'traditional_chinese': 'Traditional Chinese',

    // User Management
    'user_management': 'User Management',
    'add_user': 'Add User',
    'create_user': 'Create User',
    'new_user': 'New User',
    'role': 'Role',
    'admin': 'Admin',
    'operator': 'Operator',
    'created_at': 'Created At',
    'active': 'Active',
    'disabled': 'Disabled',
    'user_management_description': 'Create, activate, or disable user accounts.',
    'password_placeholder': 'Enter temporary password',
    'username_placeholder': 'Enter username',
    'creating_user': 'Creating user...',
    'error_creating_user': 'Error creating user.',
    'cannot_disable_admin': 'The default admin user cannot be disabled.',
    'cancel': 'Cancel',
  },
  zh: {
    // General
    'app_title': '氣膜圓頂智能儀表板',
    'select_site': '選擇站點',
    'site': '站點',
    'status': '狀態',
    'normal': '正常',
    'defect_detected': '檢測到缺陷',
    'on': '開啟',
    'off': '關閉',
    'open': '開啟',
    'closed': '關閉',
    'get_ai_analysis': '獲取 AI 分析',
    'ai_analysis_title': 'AI 圓頂健康分析',
    'generating_analysis': '正在生成分析...',
    'close': '關閉',
    'error_generating_analysis': '分析時發生錯誤，請稍後再試。',
    'historical_data': '歷史數據',
    'now_label': '現在',
    'internal': '內部',
    'external': '外部',
    'running': '運行中',
    '30_minutes': '30 分鐘',
    '1_hour': '1 小時',
    '6_hours': '6 小時',
    '12_hours': '12 小時',
    '24_hours': '24 小時',
    'logout': '登出',
    'login': '登入',
    'username': '使用者名稱',
    'password': '密碼',
    'logging_in': '正在登入...',
    'invalid_credentials': '無效的使用者名稱或密碼。',
    'dont_have_account': '沒有帳戶？',
    'register_now': '立即註冊',

    // Sites
    'site_a': '站點 A',
    'site_b': '站點 B',
    'site_c': '站點 C',

    // Views
    'dashboard': '儀表板',
    'alerts': '警報管理',
    'ventilation': '通風控制',
    'lighting': '照明控制',
    'emergency': '緊急關閉',
    'reports': '報表',
    'settings': '設置',
    'users': '使用者管理',
    
    // Paired Parameters
    'pressure': '壓力',
    'temperature': '溫度',
    'humidity': '濕度',
    'pm25': 'PM2.5',
    'co2': 'CO2',
    'o2': 'O2',
    'co': 'CO',
    'noise': '噪音',

    // Parameters
    'internal_pressure': '內部壓力',
    'external_pressure': '外部壓力',
    'fan_speed': '風扇速度',
    'air_exchange_rate': '換氣率',
    'power_consumption': '功耗',
    'voltage': '電壓',
    'current': '電流',
    'external_wind_speed': '外部風速',
    'internal_air_quality_pm25': '內部 (PM2.5)',
    'external_air_quality_pm25': '外部 (PM2.5)',
    'internal_air_quality_co2': '內部 (CO2)',
    'external_air_quality_co2': '外部 (CO2)',
    'internal_air_quality_o2': '內部 (O2)',
    'external_air_quality_o2': '外部 (O2)',
    'internal_air_quality_co': '內部 (CO)',
    'external_air_quality_co': '外部 (CO)',
    'internal_temperature': '內部溫度',
    'external_temperature': '外部溫度',
    'internal_humidity': '內部濕度',
    'external_humidity': '外部濕度',
    'membrane_health': '膜健康狀況',
    'internal_noise_level': '內部噪音水平',
    'external_noise_level': '外部噪音水平',
    'base_corner_pressure': '基座角壓力',
    'internal_lux_level': '內部光照度',
    'internal_lighting_status': '內部照明狀態',
    'air_shutter_status': '氣閘門狀態',

    // Metric Groups
    'dome_integrity': '穹頂完整性',
    'environment': '環境狀況',
    'air_quality': '空氣品質',
    'systems_status': '系統狀態',
    'power': '電力',

    // Alerts
    'active_alerts': '活躍警報',
    'alert_history': '警報歷史',
    'parameter': '參數',
    'message': '訊息',
    'severity': '嚴重性',
    'timestamp': '時間戳',
    'action': '操作',
    'high_pressure_alert': '檢測到高壓',
    'membrane_defect_alert': '檢測到潛在的膜缺陷',
    'high_co2_alert': '二氧化碳濃度過高',
    'noise_level_alert': '檢測到高噪音水平',
    'low': '低',
    'medium': '中',
    'high': '高',
    'acknowledge': '確認',
    'no_active_alerts': '此站點無活躍警報。',

    // Controls
    'ventilation_control': '通風控制',
    'lighting_control': '照明控制',
    'main_lighting': '主照明',
    'brightness': '亮度',
    'fan_set_control': '風扇組控制',
    'fan_set': '風扇組',
    'inflow_volume': '進氣量',
    'outflow_volume': '排氣量',
    'auto': '自動',
    'manual': '手動',
    'mode': '模式',
    'shutdown_fan': '關閉風扇',
    'power_on_fan': '開啟風扇',
    'power_on_lights': '開啟照明',
    'power_off_lights': '關閉照明',
    'other_controls': '其他控制',
    
    // Emergency Shutdown
    'emergency_shutdown': '緊急關閉',
    'emergency_shutdown_title': '緊急關閉協議',
    'initiate_shutdown': '啟動關閉程序',
    'shutdown_warning': '警告：此操作將立即開始全面系統關閉。這僅適用於極端緊急情況，可能需要現場人員才能完全重啟系統。',
    'confirm_shutdown_title': '需要確認',
    'confirm_shutdown_message': '您確定要關閉所有穹頂系統嗎？此操作無法從此儀表板撤銷。',
    'confirm_shutdown_button': '是的，全部關閉',
    'cancel_shutdown_button': '取消',
    'shutdown_in_progress': '正在關閉中...',
    'shutdown_step_1': '正在脫離風扇控制器...',
    'shutdown_step_2': '正在停用照明電路...',
    'shutdown_step_3': '正在鎖定氣閘門並禁用壓力傳感器...',
    'shutdown_step_4': '正在完成系統停止...',
    'shutdown_complete_title': '系統關閉完成',
    'shutdown_complete_message': '所有系統均已安全下線。穹頂現在處於安全的無動力狀態。',
    'reset_simulation': '重置模擬',

    // Reports
    'generate_report': '生成報表',
    'report_type': '報表類型',
    'time_range': '時間範圍',
    'daily': '每日',
    'weekly': '每週',
    'monthly': '每月',
    'export_pdf': '導出為 PDF',
    'export_csv': '導出為 CSV',

    // Settings
    'language_settings': '語言設置',
    'english': '英語',
    'traditional_chinese': '繁體中文',

    // User Management
    'user_management': '使用者管理',
    'add_user': '新增使用者',
    'create_user': '建立使用者',
    'new_user': '新使用者',
    'role': '角色',
    'admin': '管理員',
    'operator': '操作員',
    'created_at': '建立時間',
    'active': '啟用',
    'disabled': '停用',
    'user_management_description': '建立、啟用或停用使用者帳戶。',
    'password_placeholder': '輸入臨時密碼',
    'username_placeholder': '輸入使用者名稱',
    'creating_user': '正在建立使用者...',
    'error_creating_user': '建立使用者時發生錯誤。',
    'cannot_disable_admin': '無法停用預設的管理員使用者。',
    'cancel': '取消',
  },
};
