version: '3.8'

services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    volumes:
      - ./backend:/usr/src/app # Re-add bind mount for live code changes
      - /usr/src/app/node_modules # Anonymous volume to prevent host node_modules from overwriting container's
    # Override environment variables for local development if needed
    environment:
      - DATABASE_URL=./air_dome_dev.db # Use a separate DB for dev
      - CORS_ORIGIN=http://localhost:5173 # Your frontend dev server (Vite default)
      # You might want to use less sensitive tokens for local dev
      # - INFLUXDB_TOKEN=my-local-dev-token
      # - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-local-dev-influx-token

  influxdb:
    extends:
      file: docker-compose.yml
      service: influxdb
    volumes:
      - influxdb_dev_data:/var/lib/influxdb2 # Use a separate volume for dev InfluxDB
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=my-dev-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-dev-password
      - DOCKER_INFLUXDB_INIT_ORG=my-dev-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-dev-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-local-dev-influx-token

volumes:
  influxdb_dev_data:
  air_dome_db_dev_data: # Define the named volume for the SQLite database for dev
